spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

logging:
  level:
    com.ongodmatchu: INFO
